spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///boot
    username: root
    password: root
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      hbm2ddl.auto: update
    show-sql: true                   
        
